# This is an example docker-compose file for running OpenHound with the JAMF collector.
# the output graph will be stored inside a named volume. You can copy the OpenGraph contents using the
# following command: `<docker|podman> cp <container_name>:/tmp/output/graph <destination_path>`

x-cli: &cli
  image: specterops/openhound:latest
  restart: no
  volumes:
    - ${HOME}/.dlt/config.toml:/app/.dlt/config.toml:ro
    - jamf-output:/tmp/output

  # These environment variables can also be set inside the ~/.dlt/config.toml file
  # and act as an example. Configuring openhound can be done using environment variables,
  # configuration files or a combination of both.
  environment: &env
    LOG_LEVEL: INFO
    EXTRACT__WORKERS: 8
    LOG_CONTAINER: true

  secrets:
    - source: secrets_jamf
      target: /app/.dlt/secrets.toml

services:
  collect-jamf:
    <<: *cli
    command:
      - collect
      - jamf
      - /tmp/output/raw
      - --progress=log

  preprocess-jamf:
    <<: *cli
    command:
      - preprocess
      - jamf
      - /tmp/output/raw/jamf
      - /tmp/output/lookup.duckdb
      - --progress=log
    depends_on:
      collect-jamf:
        condition: service_completed_successfully

  convert-jamf:
    <<: *cli
    command:
      - convert
      - jamf
      - /tmp/output/raw/jamf
      - /tmp/output/graph
      - --lookup-file=/tmp/output/lookup.duckdb
      - --progress=log
    depends_on:
      preprocess-jamf:
        condition: service_completed_successfully

volumes:
  jamf-output:

secrets:
  secrets_jamf:
    file: ${HOME}/.dlt/secrets_jamf.toml
