[destination.bloodhoundenterprise]
interval = "300"
token_key = "client_token_key"
token_id = "client_token_id"
url = "bhe_url"

[sources.source.jamf]
username = "myusername"
host = "https://mytenant.jamfcloud.com"
password = "mypassword"