[destination.bloodhoundenterprise]
interval = "300"
token_key = "client_token_key"
token_id = "client_token_id"
url = "bhe_url"

[sources.source.github.credentials]
app_id = "myappid"
client_id = "myclientid"
key_path = "/app/.dlt/github.pem"
org_name = "myorgname"