[destination.bloodhoundenterprise]
interval = "300"
token_id = "client_token_id"
token_key = "client_token_key"
url = "bhe_url"

# Example configuration for jamf secrets: https://bloodhound.specterops.io/openhound/collectors/jamf/collect-data#example-configuration
[sources.source.jamf.credentials]
username = "myusername"
host = "https://mytenant.jamfcloud.com"
password = "mypassword"
