# Example configuration: https://bloodhound.specterops.io/openhound/configuration
[runtime]
http_show_error_body = true
log_cli_level = "WARNING"
log_rotate_when = "midnight"
# Default: logs are set to human readable text
# To switch to structured JSON instead, uncomment the line below (must be uppercase "JSON")
# log_format = "JSON"

[extract]
workers = 8

[normalize]
workers = 3

[load]
delete_completed_jobs = true
truncate_staging_dataset = true
