# Example configuration for github secrets: https://bloodhound.specterops.io/openhound/collectors/github/collect-data#example-configuration
[sources.source.github.credentials]
install_id = "myinstallid"
client_id = "myclientid"
key_path = "/app/.dlt/github.pem"
org_name = "myorgname"

#Example configuration for github enterprise
[sources.source.github.credentials]
app_id = "myappid"
client_id = "myclientid"
key_path = "/app/.dlt/github.pem"
enterprise_name = "myenterprisename"
